name: GitLab Runner X
description: 'Runs a gitlab runner'
author: 'Ederson Brilhante x Trung Hieu'
branding:
  icon: 'server'
  color: 'purple'
inputs:
  registration-token:
    description: 'Registration token'
    required: true
  name:
    description: 'Runner name'
    required: true
  tag-list:
    description: 'Tag list to bind with the runner'
    required: true
  docker-image:
    description: 'Docker image used by runner'
    required: false
    default: 'docker:19.03.12'
  run-untagged:
    description: "Parameter that allows or not to pick untagged jobs"
    required: false
    default: 'true'
  access-level:
    description: 'Parameter to create or not a protected runner'
    required: false
    default: "not_protected"
  server_url:
    description: 'Gitlab server url'
    required: false
    default: 'https://gitlab.com/'
  concurrent:
    description: 'Number of concurrent jobs'
    required: false
    default: '1'
  timeout:
    description: 'Time in seconds to wait for the runner to be registered, default is 60 seconds'
    required: false
    default: '21000'
runs:
  using: 'node24'
  main: 'dist/index.js'
